### PR TITLE
chore: upgrade flutter deps (flutter v3.27.0)

### PR DESCRIPTION
**Pull request by boxdot**

### CODE REVIEW

**Comment by raphaelrobert** [comment]
You could also upgrade frb to 2.7.0. That's done by changing the version [here](https://github.com/phnx-im/infra/blob/1b17ce90e24ce634012bef9785049eb0c618736e/justfile#L54) and then running `frb-generate` once to upgrade the version in both `Cargo.toml` and `pubspec.yaml`.

**Review by raphaelrobert — CHANGES_REQUESTED** [review]
I still have a warning here: https://github.com/phnx-im/infra/blob/2e1aeb46559c2eec5c48e2fb2d9b94f3b715c385/app/lib/core_client.dart#L183

`(unreachable_switch_default)`

**Comment by boxdot** [comment]
> I still have a warning here:
> 
> https://github.com/phnx-im/infra/blob/2e1aeb46559c2eec5c48e2fb2d9b94f3b715c385/app/lib/core_client.dart#L183
> 
> `(unreachable_switch_default)`

This line is actually removed in this PR. Am I missing something?

**Review by raphaelrobert — APPROVED** [review]
I was on the wrong branch, sorry.

**Pull request merged**
